### ISSUE TITLE
Django 1.10 support

### ISSUE THREAD

**Issue by jonnypickett** [bugsnag/bugsnag-python#107]
It appears that this package is not compatible with Django 1.10 because of the changes Django made to how it handles middleware.

I was able to get the middleware working by having the BugsnagMiddleware extend Django's MiddlewareMixin as described in [<a href="https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware" target="_blank">Django's 1.10 documentation regarding upgrading pre 1.10 middleware</a>](url) and using the new `MIDDLEWARE` list instead of `MIDDLEWARE_CLASSES`, but then Bugsnag failed to notify because it was saying that there was no api_key set. I'm not sure if this is due to something that has changed with the way the settings file is handled, but I have the `BUGSNAG` dictionary set in my settings.py file as described in your [<a href="https://docs.bugsnag.com/platforms/python/django/" target="_blank">Django integration guide](url).

**Comment by justinoue** [comment]
+1

**Comment by jonnypickett** [comment]
Issued pull request #108 to address this. 

If merged, the [<a href="https://docs.bugsnag.com/platforms/python/django/" target="_blank">Django integration guide</a>](url) should be updated to reflect the use of the `MIDDLEWARE` list in the settings.py file for Django >= 1.10 and the `MIDDLEWARE_CLASSES` list for Django <1.10. Thanks for the great product!

ps Turned out that the api_key not being set was an issue on my end. No worries there.

**Comment by kattrali** [comment]
Thank you for the report and contribution, @jonnypickett. Taking a look today 👀

**Comment by kattrali** [comment]
Fixed in #108

**Comment by kattrali** [comment]
Released in 3.0.0b2
