### ISSUE TITLE
Tornado exceptions captured from async functions have incorrect request context

### ISSUE THREAD

**Issue by kattrali** [bugsnag/bugsnag-python#109]
When capturing an exception which occurs within an asynchronous Tornado function, the request information is mixed with other requests happening concurrently. Investigate differentiating this information and reproducing with a simple test case.

**Comment by dacevedo12** [comment]
Same with asyncio. They are reported to bugsnag with the thread stacktrace instead of the actual code that reported.
This affects the grouping too

**Comment by jeffhunter** [comment]
@dacevedo12 last time I looked, the standard Bugsnag python code was using thread-local storage to store various pieces of configuration, which doesn't work well with async code where a thread may have numerous co-routines executing. the co-routines end up clobbering each other's bugsnag configurations, which leads to messed up stacktraces.

**Comment by phillipsam** [comment]
A fix for this has been released in [v3.7.0](https://github.com/bugsnag/bugsnag-python/releases/tag/v3.7.0)
