### ISSUE TITLE
Is there a way to filter data to send according to the release_stage directly with bugsnag ?

### ISSUE THREAD

**Issue by poulp** [bugsnag/bugsnag-python#112]
I want to send some users information when an error occur, like : 
```
user = {
    "id": user.id,
    "name": user.name,
    "email": user.email
}
```

But when the bug occurs in production i don't want to send the email. Actually i can do : 
```
if release_stage == 'prod':
    # without email
else:
    # with email
```

But it's not really funky, i'd rather want to do something like that:
```
bugsnag.exclude({
'prod': ['user_email']
})
```

**Comment by kylef** [comment]
@poulp You should be able to achieve this with a `before_notify` hook (documentation can be found at https://docs.bugsnag.com/platforms/python/customizing-error-reports/). Here you can modify the notification based on the release stage.
