### ISSUE TITLE
Choosing the right project type in Bugsnag

### ISSUE THREAD

**Issue by mjalkio** [bugsnag/bugsnag-python#129]
Hello, what's the suggested Bugsnag "Project type" if you're using the Python integration for a project that isn't Bottle, Django, Tornado, or Flask? Do you recommend "Other"? What does the project type do?

I'm currently adding Bugsnag to some scripts.

**Comment by kattrali** [comment]
Hi @mjalkio, "Other" is a fine choice for your project. Project Types promotes certain fields in error reports as are relevant to that type, such as web framework-specific features (on servers) or device-specific filters (on mobile).

**Comment by mjalkio** [comment]
Thank you @kattrali !
