### ISSUE TITLE
Flask Handler incurs BadRequest via request.get_json() with GET requests

### ISSUE THREAD

**Issue by rowedonalde** [bugsnag/bugsnag-python#142]
### Expected behavior
A loggable event transpires and the Flask handler includes the data from the request (i.e., nothing since it's a GET) in the message to bugsnag.

### Observed behavior
When request.get_json() is [called here](https://github.com/bugsnag/bugsnag-python/blob/master/bugsnag/flask/__init__.py#L23), a ValueError happens in [get_json](https://github.com/pallets/flask/blob/master/flask/wrappers.py#L75). The ValueError is raised by `json.loads(data)` because data is an empty string for a GET request, so get_json handles it by calling `on_json_loading_failed`.

### Steps to reproduce
Follow the [instructions to set up Flask integration](https://docs.bugsnag.com/platforms/python/flask/) and make an arbitrary `logger.warn('Some error message')` call somewhere in the application. The stack trace (bugsnag-python 3.4.0) or one-line message (bugsnag-python 2.3.0) should appear in your console. The message will still appear in Bugsnag in the appropriate project, though.

### Version
bugsnag-python 2.3.0 or 3.4.0 and flask 0.12

### Additional information
Changing `get_json()` to `get_json(silent=True)` [here](https://github.com/bugsnag/bugsnag-python/blob/master/bugsnag/flask/__init__.py#L23) should fix this since in that case it would return None instead of propagating an error.

**Comment by Cawllec** [comment]
Hi @rowedonalde, I can't see any stack traces or one-line messages with either version appearing in the console.  How are you setting up logging?  Are you logging through the flask app or in a separate logger?

**Comment by Cawllec** [comment]
Closing this for now, if you have any more information feel free to update this issue.

**Comment by nuronics** [comment]
how to trouble shoot that none type?
am trying to sen d request from a dialogflow(api.ai) and process the request. but the request.get_json() is reading null is there any thing i need to change in the code or dialogflow part 
thanks in advance
