### ISSUE TITLE
handle_exceptions(app) causes celery imports to change and calls to tasks to fail

### ISSUE THREAD

**Issue by bitfinity** [bugsnag/bugsnag-python#150]
### Expected behavior
*[Insert details on expected behaviour]*
It's more about the unexpected behavior

### Observed behavior
*[Insert details on observed behaviour]*
Celery tasks not being found after wrapping app in handle_exceptions(), Flask app hanging communicating with celery workier.

### Steps to reproduce
*[Insert reproduction steps (if known)]*
Celery worker running flask 0.12 with flask-sqlalchemy, factory method. Before handle_exceptions, worked fine. Afterwards, calls to import task func.delay - celery can't find task. Did you use a relative import? blah blah.

### Version
*[Insert version information]*
latest bugsnag

### Additional information
*[Insert any additional information]*
Running in docker container.

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by Cawllec** [comment]
Hi @bitfinity, I'm looking into this and will get back to you as soon as possible.

**Comment by Cawllec** [comment]
Hi @bitfinity, from testing I can't seem to reproduce the behaviour you're experiencing.  Are there any other details you can give me about how your application is set up?

**Comment by kattrali** [comment]
> Afterwards, calls to import task func.delay - celery can't find task. Did you use a relative import? blah blah.

@bitfinity Can you share a snippet of the exact error message?

**Comment by Cawllec** [comment]
@bitfinity, I'm closing this issue for now, if you have any more information, or the problem reoccurs, post here and I'll re-open this thread.
