### ISSUE TITLE
bugsnag package installing `tests`

### ISSUE THREAD

**Issue by mavin** [bugsnag/bugsnag-python#156]
### Expected behavior
The bugsnag package should only install the code needed to run the BS client.

### Observed behavior
The `tests` directory is picked up by setuptools and installed on the users machine, in the sys.path

### Steps to reproduce
On python >= 2.7.14:
1. create a vitrualenv
2. install bugsnag with pip
3. check the venv's site-packages directory for `tests`

### Version
3.4.2

**Comment by kattrali** [comment]
Thanks for the report, @mavin. It looks like we need a small tweak to `setup.py` to exclude tests from the bundled packages.

**Comment by mattdyoung** [comment]
This was previously fixed in https://github.com/bugsnag/bugsnag-python/pull/173 released in [v3.5.1](https://github.com/bugsnag/bugsnag-python/releases/tag/v3.5.1)
