### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by pior** [bugsnag/bugsnag-python#164]
### Description

This library doesn't provide type hints.

### Issue

When type checking a project, the bugsnag lib must be ignored (in Mypy config) to avoid getting 
an "import error".
Ignoring a library reduce the usefulness of type checking.

Note: once type hints are added to the project, a PEP-561 marker should be added to signal to MyPy that the package provide type hints: see https://www.python.org/dev/peps/pep-0561/

**Comment by snmaynard** [comment]
Thanks for the suggestion! We'll have a chat internally and see when we can get this scheduled.

**Comment by pior** [comment]
I don't think I will have time to open a PR for this. 
But if I can help another way, ping me!

**Comment by kylef** [comment]
For reference, I did start this over in https://github.com/bugsnag/bugsnag-python/pull/118, but there is some API surface that hasn't been audited and annotated.

As of 9ed1995, here is a report of the missing lines:

<img width="1227" alt="screenshot 2018-10-31 at 17 12 38" src="https://user-images.githubusercontent.com/44164/47825641-432d2180-dd30-11e8-8565-a4a10a94238f.png">
