### ISSUE TITLE
Failure to notify in some celery tasks

### ISSUE THREAD

**Issue by DomHudson** [bugsnag/bugsnag-python#177]
## Description
Bugsnag-python often fails to notify in processes that are due to be recycled.

## Environment

```
python:3.6.5
bugsnag==3.4.2
celery==4.1.1
Django==1.11.7
```

## Details

Celery has a setting [`worker_max_tasks_per_child`](http://docs.celeryproject.org/en/latest/reference/celery.bin.worker.html#cmdoption-celery-worker-max-tasks-per-child). Similar settings also appear in other (not celery related) multiprocessing pools. The purpose of this setting is as a safeguard against memory leaks by destroying a process after every N tasks.

Celery also has a setting [`worker_max_memory_per_child`](http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-worker_max_memory_per_child) which provides the same functionality but recyles the process based on the worker's memory consumption.

---

Both of these settings do not play well with bugsnag's `bugsnag.celery.connect_failure_handler`. If celery deems that the process is due to be replaced then bugsnag (in some cases) will not notify an unhandled exception. This is because bugsnag's default setting is to asyncronously notify. **There is a race condition between the thread that is spawned to perform the asyncronous notification and original celery process.**

The result is that in many cases celery will replace the process and the notification to bugsnag never occurs.

### Replication

- To replicate this issue, you can set `CELERY_WORKER_MAX_TASKS_PER_CHILD=1`. This will mean that the process is recycled after each task.
- Raise an exception in a celery task.
- In most cases, the HTTP request will not complete before the process is recycled, resulting in no notification to bugsnag.

### Workaround

A workaround is to use `asyncronous=False` in the bugsnag configuration. This will force the celery process to wait for the request to finish before recycling the process.

```python
import bugsnag


bugsnag.configure(
    api_key = '',
    release_stage = 'prod',
    asyncronous = False
)
```

### Solution

I believe a proper solution is to force notifying to be syncronous in `bugsnag.celery.connect_failure_handler` (and in other similar scenarios).

**Comment by kattrali** [comment]
This was fixed in bugsnag-python [v3.8.0](https://github.com/bugsnag/bugsnag-python/releases/tag/v3.8.0)
