### ISSUE TITLE
support ASGI applications

### ISSUE THREAD

**Issue by thomasleveil** [bugsnag/bugsnag-python#186]
### Description

Is there any plan to support [ASGI](https://asgi.readthedocs.io/en/latest/) web app ?

Or even better support [Starlette](https://github.com/encode/starlette) which quite a popular ASGI web framework.

**Comment by mattdyoung** [comment]
Hi @thomasleveil 

I've discussed this with our product team and although we don't have any immediate plans for this, we now plan to track interest in this and will consider it for the future roadmap.

Thanks!

**Comment by 2tunnels** [comment]
@thomasleveil you can try to use https://github.com/2tunnels/starlette-x-bugsnag

**Comment by johnkiely1** [comment]
Hi @2tunnels 

Thanks for the suggestion and sharing your work, I have added that link and your interest to the internal ticket on this.

**Comment by steve-nester-uk** [comment]
ASGI is now supported in [v.3.7.0](https://github.com/bugsnag/bugsnag-python/releases/tag/v3.7.0)
