### ISSUE TITLE
Incorrect configuration does not generate warning or error.

### ISSUE THREAD

**Issue by Ajorona** [bugsnag/bugsnag-python#193]
### Description
Improve user experience with library by validating config instead of having a silent fault. I had to set breakpoints and step through the library to determine that this was happening. It would really help improve usability if this were more explicit :)

### Issue
https://github.com/bugsnag/bugsnag-python/blob/master/bugsnag/configuration.py#L99

You intend for Configuration.should_notify to **not** send a notification to bugsnag if no release stages are specified OR if self.notify_release_stages is not a tuple or list. The problem with this is that a user can provide incorrect config values. e.g.

### (code sample to reproduce the problem)
    bugsnag.configure(
        api_key=config.get('API_KEY'),
        release_stage='staging'
        notify_release_stages='staging'
    )

This is an invalid configuration but no exception is thrown nor warning printed. Instead the bugsnag server is not notified.
If the config is not valid, then the library should let the user know that.

### Environment

Library versions:
- python version:  python 3.7
- bugsnag version: 3.6.1

**Comment by xander-jones** [comment]
Hey @Ajorona, thanks for reporting this. We're taking a look into the Python notifier at the moment, so we will take this into consideration during this work.

**Comment by phillipsam** [comment]
An update for this has now been released in [v3.8.0](https://github.com/bugsnag/bugsnag-python/releases/tag/v3.8.0)
