### ISSUE TITLE
Unable to capture errors from Django DRF application

### ISSUE THREAD

**Issue by rajeshpanda** [bugsnag/bugsnag-python#250]
I am trying to implement bugsnag on my django drf application on python 3.6+.

Here is the guide that I have followed so far - https://docs.bugsnag.com/platforms/python/django/

```
MIDDLEWARE = [
    'bugsnag.django.middleware.BugsnagMiddleware',
...
]
```

```
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'root': {
        'level': 'ERROR',
        'handlers': ['bugsnag'],
    },

    'handlers': {
        'bugsnag': {
            'level': 'INFO',
            'class': 'bugsnag.handlers.BugsnagHandler',
        },
    }
}
```

```
bugsnag.configure(
    api_key = os.environ.get("BUGSNAG_KEY"),
    project_root = BASE_DIR,
    release_stage = "dev",
)
```

AFAIK this is all that is is needed for bugnsag to start capturing the errors. But for some reason, I do not see much logs on bugsnag dashboard.
When I use a file handler instead of bugsnag one, it works like a charm and everything gets logged into the file. I read somewhere that sampling could be a reason for this.
Is that the reason or am I missing something?

Please note that, this will be deployed as an wsgi application on apache on ubuntu.

**Comment by johnkiely1** [comment]
Hi @rajeshpanda,

How are you triggering the errors?

In order to check if sampling has occurred could you let us know which organisation and project this refers to and/or provide us with some links to some of the errors you are seeing in your dashboard. 

I would suggest you contact us via suppot@bugsnag.com to provide that information.
Thanks.

**Comment by johnkiely1** [comment]
Hi @rajeshpanda,

Thanks for getting in touch via the support email channel. I have now closed this issue as we can continue the conversation via email.
