### ISSUE TITLE
input() is not working

### ISSUE THREAD

**Issue by anshumeena1947** [bugsnag/bugsnag-python#251]
### Describe the bug
this is my code check it out
x = input("enter you name: ")
print(x)

in terminal i enter
enter you name: Anshu
Traceback (most recent call last):
  File "/home/anshu/Projects/coding/python/input.py", line 2, in <module>
    x = input()
  File "<string>", line 1, in <module>
NameError: name 'Anshu' is not defined

https://user-images.githubusercontent.com/68537640/103048249-f3ff7600-45b3-11eb-9782-0e4585f4cc67.mp4

**Comment by johnkiely1** [comment]
Hi @anshumeena1947,

You should be entering "Anshu" as it expects a string.

However I believe you should be asking general python related questions like these here: https://github.com/python. This repository is for questions/issues specifically related to the use of the bugsnag-python library. 

Thanks.
