### ISSUE TITLE
Unable to set grouping_hash using `logger.<level>()` methods

### ISSUE THREAD

**Issue by cansjt** [bugsnag/bugsnag-python#253]
### Description

There is no way to change the grouping hash value when using logger methods and the BugsnagHandler to send event.

In a general manner, this module API does not make the best use of the standard logging API. That makes it very hard to integrate with existing programs and packages.

**Describe the solution you'd like**

```python
try:
     # Raising code
except:
    logger.exception("This happened", extra={'groupingHash': '<hash value>', ...})
    # Handle the exception.
```

Or to make it even less vendor specific and provide the ability to adopt Bugsnag without modifying a single line of code, while still grouping as one needs, e.g. if the grouping key to use is already available in the log record extras:

```python
import logging
root_logger = logging.getLogger()
# Note that noone should have to write such code by hand (see alternatives section below)
root_logger.addHandler(BugsnagHandler(grouping_hash='<extra-key-name>', ...))

# And later on in the code
try:
     # Raising code
except:
    logger.exception('This happened', extra={'<extra-key-name>': '<hash value>', ...})
    # Handle the exception
```

**Describe alternatives you've considered**

One way to override the `grouping_hash` so far is to use that  keyword parameter of the `bugsnag.notify()` function.
This API is really not great as it imposes to use one that is provider specific in your code when there is no need to.

Another way would be, I believe, to use a [callback](https://github.com/bugsnag/bugsnag-python/blob/master/bugsnag/handlers.py#L80). The problem with this approach is that, as currently implemented, it is not possible to pass callbacks if one wants to configure logging using a standard [configuration file](https://docs.python.org/3/library/logging.config.html). One has to make explicit calls to the `BugsnagHandler.add_callback()` method somewhere in its code. Why would you write code, to do something that should be done through configuration ?

**Additional context**

**Comment by mattdyoung** [comment]
Hi @cansjt 

Thanks for the feature request!

I can see the value in supporting something like this. It would be useful to understand more about how you're overriding the grouping hash though, as there may be a way to make the default grouping work better for you?

In terms of the alternatives you mention, our recommendation would definitely be to use a callback. You can implement a global callback at the point you initialize the Bugsnag client, and that can dynamically create a grouping hash from properties of the error report:
https://docs.bugsnag.com/platforms/python/other/customizing-error-reports/

E.g.
```
def callback(event):

    if isinstance(event.exception, SpecificError):
        event.grouping_hash = event.request.status_code

# Call `callback` before every event
bugsnag.before_notify(callback)
```

There seems less value in trying to configure a `grouping_hash` in a configuration file as you wouldn't want the same grouping hash across all the logs.

**Comment by cansjt** [comment]
Our use case is a bit specific. We are providing a data collection platform to the feature teams in our company. Hence we receive and validate data from many different sources. But we are currently struggling with notifying the right persons when some bad data is received, as technically the validation errors all look alike.

So I was hoping that, with a custom grouping, I would become able to group errors not by where they happen in the code, but by who sent us the data. Thus being able to more efficiently let people know there is an issue, and have them fix it instead of have tons of errors lingering because people don't even know they are happening.

The solution you suggest, I think, falls short for the same reasons I suggested in the last paragraph of the bug report. You are just plug-in the callback at different place. For us the right approach is to have everything work like this:

```
try:
    some_risky_call(...)
except SomeExpectedException:
    logger.exception('The worst happened !', extra={...})
```
That way, with a simple configuration, that will configure two handlers at the beginning of my program, I can send bugsnag the data I need and receive the *exact same data* in my "regular" logging stack (would it be a self hosted or managed ELK, some other SaaS provider, ...). And keep my code clean.

**Comment by mattdyoung** [comment]
Hi @cansjt 

Thanks for the info. Yes, I can see why this pattern would work well for you for your use case. This is now being considered on our backlog, although we'll need to assess the priority against other work.

One other option you'd potentially be able to use in a callback is that if the received data is in the context of an HTTP request, you could implement a callback and set the `grouping_hash` based on the header or parameters in the `event.request` object.

**Comment by johnkiely1** [comment]
Hey @cansjt. 

Just to let you know we have added this functionality in [v4.5.0](https://github.com/bugsnag/bugsnag-python/releases/tag/v4.5.0)

This can now be used like so: 
`logger.info("This happened", extra={'groupingHash': '<hash value>'})`
