### ISSUE TITLE
Missing Environment Tab

### ISSUE THREAD

**Issue by nferrara100** [bugsnag/bugsnag-python#266]
I’m using Bugsnag Python on a Django server with the following config:
 
    BUGSNAG = {
        "api_key": "xxxx",
        "project_root": BASE_DIR,
        "release_stage": RELEASE_STAGE,
        "app_version": "CI_INSERT_COMMIT_HASH",
    }
 
When I raise a random error, such with “Raise ValueError” I get a beautiful tab for the error reports in Bugsnag called “Environment” which gives me lots of debug information. It’s very useful because it includes the user agent which I can use to figure out the browser and its version.
 
Unfortunately, real world errors don’t come with the same data. It seems whenever the request tab has information there is no environment tab. The following is “Request” when I raise an error myself (which works):
```
GET
{}
POST
{}
encoding
null
headers
{}
method
GET
path
/
url
http://localhost:8000/
```
 
But if “Request” looks like this, as it typically does in the real world, I don’t see anything:
 
```
GET
{
  "from": [
    "/activities/past/"
  ],
  "period": [
    "past"
  ]
}
POST
{
  "csrfmiddlewaretoken": [
    "4caG83d6txv9YgVOTsoRAw1icKEgUoAwLgdVMXLkrXokUCTcgdeB9PtpE54L6c4q"
  ],
  "upload": [
    ""
  ]
}
encoding
null
headers
{}
method
POST
path
/view/eae8c1ff-fd5c-4970-b4df-79f2c7d79dea/
url
http://example.com/view/eae8c1ff-fd5c-4970-b4df-79f2c7d79dea/?from=/activities/past/&period=past
``` 

I tried searching your docs and issues on Github, but couldn’t find an answer. How do I always see the environment tab, or is that not possible?

I emailed the above to your support email two weeks ago but have not received a response.
 
Thank you!

**Comment by johnkiely1** [comment]
Hi @nferrara100,

Apologies, we have sent a couple of responses via the support email, perhaps they have been blocked or ended up in your spam folder for some reason?

We had some additional questions which would help us investigate this:

The environment tab should be populated with http header details when available. https://docs.bugsnag.com/platforms/python/django/automatically-captured-data/#request-information which should be a list of headers extracted from HttpRequest.META

The tab would not appear if there is no data to display, so I'm wondering if in this scenario that list is not available for some reason. 

Are you able to reproduce the scenario whereby no environment tab is shown? Could you share some example code that triggers an error like this? 
Could you tell me a little more about what is happening in the application when the "real world" errors occur. And any additional difference between your local generated error vs the real ones. Thanks

**Comment by nferrara100** [comment]
Sorry, I just noticed your emails got mixed with a rule I have for our Zendesk integration. My apologies!

To be honest, I can't recreate how I thought I got the enviornment tab. It now always looks like below.

Example:

Inside the index view on my homepage I place this code:
```
bugsnag.notify(Exception("Something broke!"))
print(request.META['HTTP_USER_AGENT'])
```

This is the request tab in Bugsnag for that request. I do not have an environment tab.
```
GET {}
POST {}
encoding null
headers {}
method GET
path /
url http://localhost:8000/
```

My console output is this:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
```

As you can see, Django can detect the useragent, but Bugsnag cannot. I am using the same very simple config listed above in my previous post. Either I'm being silly and missing something very basic (the most probable answer) or there's a bug in Bugsnag's code.

**Comment by johnkiely1** [comment]
Hi @nferrara100, 

Could you try adding the following to your configuration 
`'send_environment': True`

When using >V4 of the python notifier, which I presume you are, this is now set to false by default. 
https://github.com/bugsnag/bugsnag-python/blob/107c1add31a2202cc08ef944aa00ab96996b247a/UPGRADING.md#request-environment-configuration

**Comment by nferrara100** [comment]
Thank you! I figured I was missing something like that. Just so you know your docs have not been updated to reflect that change:

https://docs.bugsnag.com/platforms/python/other/configuration-options/#send_environment

Is there any way to parse the user agent intelligently, or will I just have to use the raw string? I'd love something like I get in the device tab for Javascript with `browserName`, `browserVersion`,  and `osName` all being distinct fields.

**Comment by nferrara100** [comment]
Also, your Django Example App link in your docs creates a Github 404. Just noticed.

**Comment by xander-jones** [comment]
Thanks for letting us know about those issues. They've been picked up in a PR for the docs that will be released soon.

The user agent is not parsed on the Bugsnag server side for Python environment. However, you can do this with a package like https://pypi.org/project/user-agents/. For example, if you're using Flask:

```py
import bugsnag
from bugsnag.flask import handle_exceptions
import user_agents

def bugsnag_add_ua_cb(event):
    ua_parsed = user_agents.parse(event.request.user_agent.string)
    event.add_tab("UA", {
        "browserName": ua_parsed.browser.family,
        "browserVersion": ua_parsed.browser.version_string,
        "osName": ua_parsed.os.family,
        "osVersion": ua_parsed.os.version_string
    })

bugsnag.configure(
	# ...
)
bugsnag.before_notify(bugsnag_add_ua_cb)
```

Which will result in something as follows:

![image](https://user-images.githubusercontent.com/9535852/120500744-fbc01380-c3b8-11eb-8193-212e9a9e5781.png)

Closing out the issue as the original question has been solved, and we'll merge in the docs updates soon! 😄
