### ISSUE TITLE
Gunicorn timeout errors not being reported

### ISSUE THREAD

**Issue by Morantron** [bugsnag/bugsnag-python#293]
### Describe the bug

Similar to https://github.com/getsentry/sentry-python/issues/510, worker timeout errors are not logged in bugsnag.

### Steps to reproduce

1. Have an app running with gunicorn (default timeout is 30s).
2. Add a 60s delay in some endpoint and hit it.
3. `[2279753] [CRITICAL] WORKER TIMEOUT` will be seen in the logs, but nothing will be tracked in bugsnag.

### Environment
* Bugsnag version: 3.6.1
* Python version: 3.8.6
* Integration framework version:
    * Django: 2.2.17

**Comment by luke-belton** [comment]
Hi @Morantron,

Have you tried connecting your gunicorn logs to Bugsnag's Handler? [It looks like gunicorn uses Python's standard logging config file](https://docs.gunicorn.org/en/latest/settings.html#logconfig) so this should be possible to capture the `[CRITICAL] WORKER TIMEOUT` errors.

Please can you give that a try and let us know how you get on? If you have any other questions please let us know!
