### ISSUE TITLE
Move cookies into their own tab

### ISSUE THREAD

**Issue by loopj** [bugsnag/bugsnag-python#30]
Our ruby notifier has cookies in their own tab, whereas in python we nest them under the request tab. They are much more readable in their own tab, so I propose we move cookies to their own tab in python too.

**Comment by kattrali** [comment]
Given that we [filter cookies by default](https://github.com/bugsnag/bugsnag-python/blob/a20fd7f58543d5d9afa4bdb755e59343abf57a29/bugsnag/configuration.py#L52) for security reasons, should cookies be removed altogether?

**Comment by snmaynard** [comment]
To me, removing cookies seems like a good idea. People should add them in if they want them.

We used to send everything, env and cookies - but there are so many complications that I would disable sending them by default across the board and we have moved in that direction in most, if not all notifiers.
