### ISSUE TITLE
program gets stuck if notify.bugsnag.com is blocked (pi hole)

### ISSUE THREAD

**Issue by benedikt-hess-km** [bugsnag/bugsnag-python#300]
### Describe the bug
I am using a pi hole in my network. I did not know `notify.bugsnag.com` was blocked. When i tried to raise an error to test my settings, i was caught in an endless loop. From what i saw, bugsnag tried to send a report, an SSL error was thrown (`requests.exceptions.SSLError`), this was caught by bugsnag, which tried to notify again and so on.

### Steps to reproduce
1. block `notify.bugsnag.com` with a pihole (and use this pihole as your DNS server ;) )
2. initialize bugsnag and do not change the `auto_notify` in configure (defaults to `True`) e.g.:
```
import bugsnag

bugsnag.configure(api_key=BUGSNAG_API_KEY,)
```
3. Raise an error (also works with notify and error logs)
```
raise ValueError
```
4. You are now stuck

When adding `requests.exceptions.SSLError` to the `ignore_classes` this can be avoided.

I know that the initial problem was caused by my DNS blocking. However, failing to publish to bugsnag should not cause the program to get stuck in a loop. If you need any additional information, let me know.

Greetings Bene

### Environment
* Bugsnag version: 4.1.1
* Python version: 3.9.5

**Comment by benedikt-hess-km** [comment]
I just ran another test. The same thing happens if you disable your internet connection.

**Comment by johnkiely1** [comment]
Hi @benedikt-hess-km. 

Thanks for reporting. We are going to take a look and see what we can do to fix it.
