### ISSUE TITLE
DeprecationWarning: The Event "metadata" argument has been replaced with "metadata" - Typo

### ISSUE THREAD

**Issue by taracha-r** [bugsnag/bugsnag-python#321]
### Describe the bug
typo in Depercation warning

it should be `DeprecationWarning: The Event "meta_data" argument has been replaced with "metadata"`

### Steps to reproduce
![image](https://user-images.githubusercontent.com/7542220/173654706-7c45988e-5aed-49d0-b996-a0db0fc8fa8d.png)

### Environment
* Bugsnag version: 4.2.1
* Python version: 3.9.13
* Integration framework version:
    * ASGI: Daphne
    * Celery: 5.2
    * Django: 4.0

**Comment by johnkiely1** [comment]
Hi @taracha-r, 
Thanks for raising, we will look to get this corrected when we can.
