### ISSUE TITLE
_code_for Window Size as Option 

### ISSUE THREAD

**Issue by dem-ola** [bugsnag/bugsnag-python#322]
### Description
The standard number of stacktrace lines is 7, hardcoded in the argument for the _code_for method of class Event. Bugsnag monitoring is a key collaboration tool at work and we've found ourselves almost always wishing there was more context around the error line.

**Describe the solution you'd like**
An ability to override the window_size argument probably as a configuration parameter. The Event class takes in the bugsnag configuration on initialization and the window_size could be retrieved from self.config and set as the window_size or if none then use the default 7.

**Describe alternatives you've considered**
I thought it might be possible to subclass Event and override _code_for but I couldn't figure out how to do this within our app.

**Additional context**

**Comment by luke-belton** [comment]
Hi @dem-ola - thanks for raising this, I've shared it with our product team for their consideration and will let you know if we have any updates in this area.

In the meantime you could setup source control links with your code (i.e. [by notifying us of your builds](https://docs.bugsnag.com/build-integrations/#if-your-build-tool-is-not-supported)). This would allow you to navigate directly from the event in Bugsnag to your source code at the relevant commit for the event's release, giving you more context that way.
![Screenshot 2022-07-21 at 12 05 22](https://user-images.githubusercontent.com/58511679/180199347-b31c8357-6915-4daf-af87-bf77ff04b1f0.png)

**Comment by luke-belton** [comment]
Hi @dem-ola - just following up on this as we haven't heard from you in a while. The problem with making the number of lines of code configurable is that it would potentially break grouping, which uses surrounding code when that is available. I'm going to close this issue for now as hopefully you'll be able to use the source control links workaround I suggested above to get additional context on your events 👍
