### ISSUE TITLE
Missing clear call in asgi middleware

### ISSUE THREAD

**Issue by dacevedo12** [bugsnag/bugsnag-python#369]
### Describe the bug
https://github.com/bugsnag/bugsnag-python/blob/master/bugsnag/asgi.py seems to be missing a 
```python
finally:
            bugsnag.clear_request_config()
```

just like its wsgi counterpart

**Comment by clr182** [comment]
Hi @dacevedo12  

Thanks for reaching out. Have you received any errors/issues relating to this missing finally call? If so could you please elaborate on the error or issue you have seen?

**Comment by dacevedo12** [comment]
I was trying to use a callback and get some data from `event.request`, then I felt curious as to how bugsnag knew which request was active at the time of the error.

Digging in the code I discovered the `configure_request` call at https://github.com/bugsnag/bugsnag-python/blob/master/bugsnag/asgi.py#L119C9-L119C34 but then I couldn't find the call where it clears it up
