### ISSUE TITLE
There should be a way to add to the request metadata, instead of overwriting it

### ISSUE THREAD

**Issue by singingwolfboy** [bugsnag/bugsnag-python#40]
Right now, there's only the option to clobber the request metadata. It would be nice to be able to add to it over the course of the request, rather than resetting it every time.

**Comment by singingwolfboy** [comment]
This is *way* better than it was, thanks! However, if I put in a pull request to change the API that this exposes, would that be considered/accepted? `bugsnag.add_metadata_tab("account", {"premium": True})` doesn't seem very Pythonic, and I feel like it would be better if you could just do `bugsnag.request_context["account"] = {"premium": True}`, or `bugsnag.request_context["account"]["premium"] = True`

**Comment by ConradIrwin** [comment]
That would definitely be accepted :).

Thanks!

Conrad
