### ISSUE TITLE
Configurable logging

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-python#43]
We should have more configurable logging, possibly with loggers ala bugsnag-ruby

**Comment by lwcolton** [comment]
Can you elaborate on this?

**Comment by kattrali** [comment]
@snmaynard Did you mean like #64, or something else?

**Comment by snmaynard** [comment]
This issue meant to mean logging from within the library - so having debug logging for when the library isnt doing what you think it should. Sometimes in the ruby notifier I get people to make the logging more verbose and we log things like the payload sent etc. Does that make sense?

**Comment by kattrali** [comment]
Gotcha. Yeah that makes sense.

**Comment by kattrali** [comment]
This is possible now using `bugsnag.logger.setLevel()`, though there isn’t anything being logged at a debug level yet.

**Comment by kattrali** [comment]
Fixed in v3.0.0b1
