### ISSUE TITLE
Django support broken in 2.0.2

### ISSUE THREAD

**Issue by arski** [bugsnag/bugsnag-python#45]
I just updated from 2.0.1 to 2.0.2 and while before it used to work, now I get `** [Bugsnag] No API key configured, couldn't notify` with exactly the same code other than the upgraded bugsnag-python package.

It seems that notifications on requests (i.e. when someone access the webpage and gets an error) still work, but when say a cronjob worker encounters an error somewhere in the backend processing code, it throws me that :/

let me know if I can provide any more info

**Comment by ConradIrwin** [comment]
Is this fixed in `2.2.0
