### ISSUE TITLE
Shouldn't Python logging handler take `notify_release_stages` into account ?

### ISSUE THREAD

**Issue by zemanel** [bugsnag/bugsnag-python#51]
`notify_release_stages` which is part of the configuration is not taken into account in the logging handler (afaik).

When both Django middleware and logging handler are configured (which is useful to handle exceptions in middlewares for example), the logging handler always emits a notification.

**Comment by stevelacey** [comment]
I am pretty sure this is works as described and that our (@zemanel and I's) `settings.py` was just a bit of a mess and the release_stage was getting set wrong.

**Comment by ConradIrwin** [comment]
Ok, going to close this then :).
