### ISSUE TITLE
Security Risk by including HTTP Headers

### ISSUE THREAD

**Issue by lwcolton** [bugsnag/bugsnag-python#55]
Our Bugsnag is configured using the Django method.  When a Django request has an error, Bugsnag logs all sorts of useful info about the request.  Like HTTP headers.  Including a header called HTTP_COOKIE.  This contains cookie information like session ID's which are sensitive and recording them in Bugsnag could violate privacy concerns.  Depending on the application, other HTTP headers could contain information that is just as sensitive.  Recommend disabling the recording of HTTP_* variables in Django (headers) by default.  Also recommend allowing easier blacklisting or whitelisting of which headers to include, via a dictionary rather than a before_notify callback.  Related #30 , maybe both issues could be solved by the same changeset.

**Comment by ConradIrwin** [comment]
Fixed in v2.3.1 by adding "cookie" and "authorization" to the default filters. We've done this with our ruby notifier already.
