### ISSUE TITLE
404 should be sent as warnings, not errors

### ISSUE THREAD

**Issue by hakanw** [bugsnag/bugsnag-python#56]
I know there's a way to silence 404's altogether, but I think it's useful that they are reported to bugsnag. But it's usually not the case that a 404 is a hard application error. Therefore I think the default should be to send it as a warning.

**Comment by snmaynard** [comment]
You can use our [existing callbacks](https://github.com/bugsnag/bugsnag-python#before-notify-callbacks) to do this already. Just set `notification.severity = "warning"` in the case that its a 404.
