### ISSUE TITLE
User not set correctly when using custom auth in django

### ISSUE THREAD

**Issue by justmobilize** [bugsnag/bugsnag-python#62]
In the line:

```
notification.set_user(id=request.user.username, email=request.user.email, name=name)
```

It assumes that the username field is username. In custom authentication this isn't guaranteed to exist. You should do:

```
notification.set_user(id=request.user.get_username(), email=request.user.email, name=name)
```

**Comment by martinse** [comment]
Also the name of the user assumes that the fields `first_name` and `last_name` exists which are marked as optional in the User module. Better would be to use `get_full_name()` which is present both in `User` and `CustomUser`.

https://docs.djangoproject.com/en/dev/topics/auth/customizing/#django.contrib.auth.models.CustomUser.get_full_name
