### ISSUE TITLE
Request: Include logging in configuration

### ISSUE THREAD

**Issue by Bekt** [bugsnag/bugsnag-python#64]
Instead of manually hooking up `BugsnagHandler` somewhere in the application, it would be cleaner to have an option in `bugsnag.configure` to enable logging, something like what Sentry [does](https://docs.getsentry.com/hosted/clients/python/integrations/flask/#extended-setup):

```python
sentry = Sentry()

def create_app():
    app = Flask(__name__)
    sentry.init_app(app, dsn='http://public_key:secret_key@example.com/1',
                    logging=True, level=logging.ERROR)
    return app
```

**Comment by Bekt** [comment]
I can submit a really quick change for my specific case (Flask), but the maintainers probably should write a more generic solution.

**Comment by Bekt** [comment]
Ping.

**Comment by kattrali** [comment]
Hi @Bekt, thanks for the suggestion. I think a logging configuration would be a great addition. If you are (still) willing to make a Flask-specific implementation, I think I can put together a more generic version for other frameworks.

**Comment by Bekt** [comment]
Ah sorry, I'm not using bugsnag anymore.

**Comment by kattrali** [comment]
Thanks for the update! Drafting a new issue for a logging-based configuration.
