### ISSUE TITLE
How do I view local variables when exception happens in Python(Django).

### ISSUE THREAD

**Issue by m4tech** [bugsnag/bugsnag-python#66]
We need a way such that we can view local variable for stack trace in your Error dashboard. Is there any way for this current??.  This feature is already provided by www.getsentry.com

**Comment by m4tech** [comment]
Got this reply from Bugsnag team:

We do not automatically send local variables with the error but you can send additional metadata (such as local variables) along with each error report for display in another tab.

This can be done by calling bugsnag.add_metadata_tab (e.g. bugsnag.add_metadata_tab("account", {"premium": True})). 

Please see https://bugsnag.com/docs/notifiers/python for more information

**Comment by lcmartinezdev** [comment]
It has been a long time since this question was created.
Is it possible that this has been worked on, is there any news?

**Comment by johnkiely1** [comment]
Hi @lcmartinezdev. 

For handled errors you can enable local variable capture: https://docs.bugsnag.com/platforms/python/django/reporting-handled-errors/#capturing-local-variables.
