### ISSUE TITLE
INFO events are posted to bugsnag when using logging framework

### ISSUE THREAD

**Issue by veverjak** [bugsnag/bugsnag-python#80]
Hi, 

I want to use bugsnag to notify me when error message is logged. I have following setup:
```
    bugsnag.configure(
        api_key = _BUGSNAG_API_KEY
    )

    logger = logging.getLogger(__name__)
    logger.setLevel(logging.INFO)

    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)
    formatter = logging.Formatter(_LOG_FORMAT)
    ch.setFormatter(formatter)

    logger.addHandler(ch)
    logger.addHandler(BugsnagHandler())
```

but I can see INFO messages in our bugsnag. 
I was expecting only > ERROR messages are sent to bugsnag. 

Do I have incorrect setup or is this expected behavior?

**Comment by kattrali** [comment]
Thanks for the report, @veverjak. There's a small configuration tweak to reduce the logging information sent. By default, the `BugsnagHandler` will pass along any log messages sent, including `INFO`-level ones, as some find it useful. However, it has the [`logging.Handler`](https://docs.python.org/2/library/logging.html#handler-objects) base class and can have a custom level set like so:

```python
handler = BugsnagHandler()
handler.setLevel(logging.ERROR)
logger.addHandler(handler)
```

**Comment by veverjak** [comment]
Neat, thanks @kattrali. 
It was only little unclear from docs: ["You can also hook Bugsnag up to Python's logging framework so that anything of level error or above is logged to Bugsnag."](https://bugsnag.com/docs/notifiers/python)

**Comment by EpocDotFr** [comment]
Stumbled on the same invalid documentation sentence. Our Bugsnag is now full of INFO logs.

**Comment by jmeridth** [comment]
The fine folks on the Twitter bugsnag account filed a bug and got this fixed. Docs have been updated. https://docs.bugsnag.com/platforms/python/other
