### ISSUE TITLE
Writing to stdout on Every Submission is Unnecessary

### ISSUE THREAD

**Issue by reverendj1** [bugsnag/bugsnag-python#81]
Every time something is logged to BugSnag,

> ** [Bugsnag] Notifying https://notify.bugsnag.com of exception

is printed to stdout. This seems rather superfluous and more like debugging info. It would be nice if there were an option to disable the messages. It can be distracting for user-facing, interactive scripts where you may want to pretty up errors before displaying them, etc.

**Comment by kattrali** [comment]
Thank you for the report, @reverendj1. Always printing debugging info is unnecessary in day-to-day execution and should be configurable. I'm going to merge and close this into #43, which should evolve into a proper logger.
