### ISSUE TITLE
Error display on bug snag as well as on termnial

### ISSUE THREAD

**Issue by scottydelta** [bugsnag/bugsnag-python#82]
After integrating bugsnag with my flask app, I dont see errors on my terminal anymore, how can I force errors to be displayed both on bugsnag and terminal? Is it possible to only log errors on prod?

**Comment by kattrali** [comment]
> I dont see errors on my terminal anymore, how can I force errors to be displayed both on bugsnag and terminal?

If using the logging integration, this may have been a case of either needing to also add a [`StreamHandler`](https://docs.python.org/3.5/library/logging.handlers.html#logging.StreamHandler) in addition to the Bugsnag handler to send errors to both places, or needing to set  [`propagate` to `True` on a child logger](https://docs.python.org/3.5/library/logging.html#logging.Logger.propagate).

> Is it possible to only log errors on prod?

Logging errors to only certain environments (like production) is available using the [`notify_release_stages`](https://docs.bugsnag.com/platforms/python/flask/configuration-options/#notify_release_stages) configuration option. If the current [`release_stage`](https://docs.bugsnag.com/platforms/python/flask/configuration-options/#release_stage) is not present in `notify_release_stages`, no report will be sent.
