### ISSUE TITLE
Django: Request information is missing when SessionMiddleware is not enabled

### ISSUE THREAD

**Issue by phwh** [bugsnag/bugsnag-python#84]
Hello,

Django request logging didn't work for me with Bugsnag. Altough all exceptions show up in Bugsnag they are missing information about the requests (URL, HTTP method, GET and POST params etc).

I think I found the cause:
Line 35 in `bugsnag/django/__init__.py` accesses the `request.session` object (v2.4.0). But since our project doesn't use sessions (`SessionMiddleware` is not enabled) there is no `request.session` object present. So the call fails.

Somehow the exception is logged nevertheless and shows up in Bugsnag but the request information, which is added after line 35, is missing.

**Comment by kattrali** [comment]
Thank you for the report @phwh, and for that bit of detective work. I'll make a patch to adjust this behavior when `request.session` is not present, as it should not have been an assumption anyway.

**Comment by kattrali** [comment]
Released in [2.5.0](https://github.com/bugsnag/bugsnag-python/blob/master/CHANGELOG.md#250-2016-06-14)
